/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_edma.h"
#include "stdlib.h"
#include "fsl_common.h"
#include "fsl_spc.h"
#include "fsl_vref.h"
#include "fsl_lpadc.h"
#include "fsl_ctimer.h"
#include "fsl_clock.h"
#include "fsl_gpio.h"
#include "fsl_lpi2c.h"
#include "fsl_lpi2c_edma.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR (EDMA_Type *)DMA0

  /* Channel CH0 definitions */
/* DMA0 eDMA source request. */
#define DMA0_CH0_DMA_REQUEST kDma0RequestMuxAdc0FifoARequest
/* Selected eDMA channel number. */
#define DMA0_CH0_DMA_CHANNEL 0
/* TCD structure index 0 definition */
#define DMA0_CH0_TCD0_CONFIG DMA0_CH0_TCDs_config[0]
/* TCD structure index 1 definition */
#define DMA0_CH0_TCD1_CONFIG DMA0_CH0_TCDs_config[1]
/* Definition of peripheral ID */
#define VREF0_PERIPHERAL VREF0
/* Alias for ADC0 peripheral */
#define ADC0_PERIPHERAL ADC0
/* Command 1 - POT */
#define ADC0_POT 1U
/* Command 2 - LIGHT */
#define ADC0_LIGHT 2U
/* Definition of peripheral ID */
#define CTIMER0_PERIPHERAL CTIMER0
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER0_TICK_FREQ 1000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER0_TICK_PERIOD 1000000UL
/* Definition of PWM period channel. */
#define CTIMER0_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 3 ID */
#define CTIMER0_MATCH_3_CHANNEL kCTIMER_Match_3
/* Definition of channel 0 ID */
#define CTIMER0_MATCH_0_CHANNEL kCTIMER_Match_0
/* CTIMER0 interrupt vector ID (number). */
#define CTIMER0_TIMER_IRQN CTIMER0_IRQn
/* CTIMER0 interrupt vector priority. */
#define CTIMER0_TIMER_IRQ_PRIORITY 2
/* NVIC interrupt vector ID (number). */
#define INT_0_IRQN EDMA_0_CH1_IRQn
/* NVIC interrupt vector priority. */
#define INT_0_IRQ_PRIORITY 2
/* NVIC interrupt handler identifier. */
#define INT_0_IRQHANDLER EDMA_0_CH1_IRQHandler
/* Alias for GPIO2 peripheral */
#define GPIO2_GPIO GPIO2
/* Alias for PORT2 */
#define GPIO2_PORT PORT2
/* GPIO2 interrupt vector ID (number). */
#define GPIO2_INT_0_IRQN GPIO20_IRQn
/* GPIO2 interrupt vector priority. */
#define GPIO2_INT_0_IRQ_PRIORITY 2
/* GPIO2 interrupt handler identifier. */
#define GPIO2_INT_0_IRQHANDLER GPIO20_IRQHandler
/* Alias for GPIO1 peripheral */
#define GPIO1_GPIO GPIO1
/* Alias for PORT1 */
#define GPIO1_PORT PORT1
/* GPIO1 interrupt vector ID (number). */
#define GPIO1_INT_0_IRQN GPIO10_IRQn
/* GPIO1 interrupt vector priority. */
#define GPIO1_INT_0_IRQ_PRIORITY 2
/* GPIO1 interrupt handler identifier. */
#define GPIO1_INT_0_IRQHANDLER GPIO10_IRQHandler
/* Alias for GPIO4 peripheral */
#define GPIO4_GPIO GPIO4
/* Alias for PORT4 */
#define GPIO4_PORT PORT4
/* GPIO4 interrupt vector ID (number). */
#define GPIO4_INT_0_IRQN GPIO40_IRQn
/* GPIO4 interrupt vector priority. */
#define GPIO4_INT_0_IRQ_PRIORITY 2
/* GPIO4 interrupt handler identifier. */
#define GPIO4_INT_0_IRQHANDLER GPIO40_IRQHandler
/* BOARD_InitPeripherals defines for LP_FLEXCOMM2 */
/* Definition of peripheral ID */
#define LP_FLEXCOMM2_PERIPHERAL LPI2C2
/* Definition of peripheral base address */
#define LP_FLEXCOMM2_PERIPHERAL_BASE LPI2C2_BASE
/* Definition of the clock source frequency */
#define LP_FLEXCOMM2_CLOCK_SOURCE 12000000UL
/* LP_FLEXCOMM2 eDMA source request. */
#define LP_FLEXCOMM2_RX_DMA_REQUEST kDma0RequestMuxLpFlexcomm2Rx
/* Selected eDMA channel number. */
#define LP_FLEXCOMM2_RX_DMA_CHANNEL 2
/* Used DMA device. */
#define LP_FLEXCOMM2_RX_DMA_BASEADDR DMA0
/* LP_FLEXCOMM2 eDMA source request. */
#define LP_FLEXCOMM2_TX_DMA_REQUEST kDma0RequestMuxLpFlexcomm2Tx
/* Selected eDMA channel number. */
#define LP_FLEXCOMM2_TX_DMA_CHANNEL 1
/* Used DMA device. */
#define LP_FLEXCOMM2_TX_DMA_BASEADDR DMA0
/* Alias for GPIO3 peripheral */
#define GPIO3_GPIO GPIO3
/* Alias for PORT3 */
#define GPIO3_PORT PORT3
/* GPIO3 interrupt vector ID (number). */
#define GPIO3_INT_0_IRQN GPIO30_IRQn
/* GPIO3 interrupt vector priority. */
#define GPIO3_INT_0_IRQ_PRIORITY 2
/* GPIO3 interrupt handler identifier. */
#define GPIO3_INT_0_IRQHANDLER GPIO30_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern edma_config_t DMA0_config;
/* Destination address declaration */
extern volatile uint16_t potValue;
/* Destination address declaration */
extern volatile uint16_t lightValue;
/* TCD configuration */
AT_NONCACHEABLE_SECTION_ALIGN_INIT(extern edma_tcd_t DMA0_CH0_TCDs_config[2], 0x20U);
extern const lpadc_config_t ADC0_config;
extern lpadc_conv_command_config_t ADC0_commandsConfig[2];
extern lpadc_conv_trigger_config_t ADC0_triggersConfig[1];
extern const ctimer_config_t CTIMER0_config;
extern const ctimer_match_config_t CTIMER0_Match_3_config;
extern const ctimer_match_config_t CTIMER0_Match_0_config;
extern const lpi2c_master_config_t LP_FLEXCOMM2_masterConfig;
extern edma_handle_t LP_FLEXCOMM2_RX_Handle;
extern edma_handle_t LP_FLEXCOMM2_TX_Handle;
extern lpi2c_master_edma_handle_t LP_FLEXCOMM2_master_handle;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
  /* Single callback function declaration */
extern void ctimer0_callback(uint32_t flags);
extern ctimer_callback_t CTIMER0_callback[];
/* eDMA LPI2C leader callback function for the LP_FLEXCOMM2 component (init. function BOARD_InitPeripherals)*/
extern void lpi2c_master_callback(LPI2C_Type *, lpi2c_master_edma_handle_t *, status_t, void *);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
