/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MCXN947
package_id: MCXN947VDF
mcu_data: ksdk2_0
processor_version: 25.12.10
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: f86062b4-3550-46b9-a557-ef5c23e74c46
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'edma4'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'edma4_2.9.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_edma:
    - dmamux_devices: []
    - common_settings:
      - vars: []
      - enableHaltOnError: 'true'
      - enableDebugMode: 'false'
      - enableRoundRobinArbitration: 'fixedPriority'
      - enableGlobalChannelLink: 'true'
      - enableMasterIdReplication: 'false'
    - dma_table:
      - 0: []
      - 1: []
      - 2: []
    - edma_channels:
      - 0:
        - apiMode: 'nontransTCD'
        - edma_channel:
          - channel_prefix_id: 'CH0'
          - uid: '1773175247801'
          - eDMAn: '0'
          - eDMA_source: 'kDma0RequestMuxAdc0FifoARequest'
          - init_channel_priority: 'false'
          - edma_channel_Preemption:
            - enableChannelPreemption: 'false'
            - enablePreemptAbility: 'false'
            - channelPriority: '0'
          - masterIdReplicationEnable: 'noInit'
          - securityLevel: 'noInit'
          - protectionLevel: 'noInit'
        - resetChannel: 'false'
        - enableChannelRequest: 'true'
        - enableAsyncRequest: 'false'
        - tcd_configuration:
          - 0:
            - TCD_REGS:
              - edma4_tcd: []
            - uid: '1773304327639'
            - tcdID: 'CH0_TCD0'
            - ssize: 'kEDMA_TransferSize2Bytes'
            - saddr_expr: '&(ADC0->RESFIFO[0])'
            - saddr_def: ''
            - soff: '0'
            - soff_def: ''
            - smod: 'kEDMA_ModuloDisable'
            - dsize: 'kEDMA_TransferSize2Bytes'
            - daddr_expr: '&potValue'
            - daddr_def: 'extern volatile uint16_t potValue;'
            - doff: '0'
            - doff_def: ''
            - dmod: 'kEDMA_ModuloDisable'
            - nbytes: '2'
            - MLconfig:
              - offsetType: 'disabled'
              - mloff: '0'
            - enableChannelLinkMinor: 'false'
            - linkedChannelMinor: '1773175247801'
            - bandwidthControl: 'disabled'
            - citer: '1'
            - slast: '0'
            - esda: 'false'
            - eeop: 'false'
            - enableChannelLinkMajor: 'false'
            - linkedChannelMajor: '1773175247801'
            - disableERQ: 'false'
            - enableScatterGather: 'true'
            - sga: '1773833603239'
            - interruptSources: ''
          - 1:
            - TCD_REGS:
              - edma4_tcd: []
            - uid: '1773833603239'
            - tcdID: 'CH0_TCD1'
            - ssize: 'kEDMA_TransferSize2Bytes'
            - saddr_expr: '&(ADC0->RESFIFO[0])'
            - saddr_def: ''
            - soff: '0'
            - soff_def: ''
            - smod: 'kEDMA_ModuloDisable'
            - dsize: 'kEDMA_TransferSize2Bytes'
            - daddr_expr: '&lightValue'
            - daddr_def: 'extern volatile uint16_t lightValue;'
            - doff: '0'
            - doff_def: ''
            - dmod: 'kEDMA_ModuloDisable'
            - nbytes: '2'
            - MLconfig:
              - offsetType: 'disabled'
              - mloff: '0'
            - enableChannelLinkMinor: 'false'
            - linkedChannelMinor: '1773175247801'
            - bandwidthControl: 'disabled'
            - citer: '1'
            - slast: '0'
            - esda: 'false'
            - eeop: 'false'
            - enableChannelLinkMajor: 'false'
            - linkedChannelMajor: '1773175247801'
            - disableERQ: 'false'
            - enableScatterGather: 'true'
            - sga: '1773304327639'
            - interruptSources: ''
        - constantTCD: 'false'
        - no_init_uid: '1773175247820'
        - initializedTCD: '1773304327639'
        - channel_enabled_interrupts: ''
        - init_interruptsEnable: 'false'
        - interrupt_channel:
          - IRQn: 'EDMA_0_CH0_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
edma_config_t DMA0_config = {
  .enableMasterIdReplication = false,
  .enableGlobalChannelLink = true,
  .enableHaltOnError = true,
  .enableDebugMode = false,
  .enableRoundRobinArbitration = false
};
AT_NONCACHEABLE_SECTION_ALIGN_INIT(edma_tcd_t DMA0_CH0_TCDs_config[2], 0x20U)
 = {
  {
    .TCD_REGS = {
      .edma4_tcd = {
        .SADDR = (uint32_t) &(ADC0->RESFIFO[0]),
        .SOFF = (uint16_t) 0,
        .ATTR = DMA_TCD_ATTR_SMOD(kEDMA_ModuloDisable) | DMA_TCD_ATTR_SSIZE(kEDMA_TransferSize2Bytes) | DMA_TCD_ATTR_DMOD(kEDMA_ModuloDisable) | DMA_TCD_ATTR_DSIZE(kEDMA_TransferSize2Bytes),
        .NBYTES = DMA_TCD_NBYTES_MLOFFNO_NBYTES(2UL) | DMA_TCD_NBYTES_MLOFFNO_SMLOE(0U) | DMA_TCD_NBYTES_MLOFFNO_DMLOE(0U),
        .SLAST = DMA_TCD_SLAST_SDA_SLAST_SDA(0UL),
        .DADDR = (uint32_t) &potValue,
        .DOFF = (uint16_t) 0,
        .CITER = DMA_TCD_CITER_ELINKNO_ELINK(0U) | DMA_TCD_CITER_ELINKNO_CITER(1U),
        .DLAST_SGA = (uint32_t)(&DMA0_CH0_TCD1_CONFIG),
        .CSR = DMA_TCD_CSR_START(0U) | DMA_TCD_CSR_INTMAJOR(0U) | DMA_TCD_CSR_INTHALF(0U) | DMA_TCD_CSR_DREQ(0U) | DMA_TCD_CSR_ESG(1U) | DMA_TCD_CSR_BWC(0U) | DMA_TCD_CSR_ESDA(0U) | DMA_TCD_CSR_EEOP(0U) | DMA_TCD_CSR_MAJORELINK(0U) | DMA_TCD_CSR_MAJORLINKCH(0),
        .BITER = DMA_TCD_BITER_ELINKNO_ELINK(0U) | DMA_TCD_BITER_ELINKNO_BITER(1U)
      }
    }
  },
  {
    .TCD_REGS = {
      .edma4_tcd = {
        .SADDR = (uint32_t) &(ADC0->RESFIFO[0]),
        .SOFF = (uint16_t) 0,
        .ATTR = DMA_TCD_ATTR_SMOD(kEDMA_ModuloDisable) | DMA_TCD_ATTR_SSIZE(kEDMA_TransferSize2Bytes) | DMA_TCD_ATTR_DMOD(kEDMA_ModuloDisable) | DMA_TCD_ATTR_DSIZE(kEDMA_TransferSize2Bytes),
        .NBYTES = DMA_TCD_NBYTES_MLOFFNO_NBYTES(2UL) | DMA_TCD_NBYTES_MLOFFNO_SMLOE(0U) | DMA_TCD_NBYTES_MLOFFNO_DMLOE(0U),
        .SLAST = DMA_TCD_SLAST_SDA_SLAST_SDA(0UL),
        .DADDR = (uint32_t) &lightValue,
        .DOFF = (uint16_t) 0,
        .CITER = DMA_TCD_CITER_ELINKNO_ELINK(0U) | DMA_TCD_CITER_ELINKNO_CITER(1U),
        .DLAST_SGA = (uint32_t)(&DMA0_CH0_TCD0_CONFIG),
        .CSR = DMA_TCD_CSR_START(0U) | DMA_TCD_CSR_INTMAJOR(0U) | DMA_TCD_CSR_INTHALF(0U) | DMA_TCD_CSR_DREQ(0U) | DMA_TCD_CSR_ESG(1U) | DMA_TCD_CSR_BWC(0U) | DMA_TCD_CSR_ESDA(0U) | DMA_TCD_CSR_EEOP(0U) | DMA_TCD_CSR_MAJORELINK(0U) | DMA_TCD_CSR_MAJORLINKCH(0),
        .BITER = DMA_TCD_BITER_ELINKNO_ELINK(0U) | DMA_TCD_BITER_ELINKNO_BITER(1U)
      }
    }
  }
};

static void DMA0_init(void) {

  /* Channel CH0 initialization */
  /* Set the kDma0RequestMuxAdc0FifoARequest request */
  EDMA_SetChannelMux(DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL, DMA0_CH0_DMA_REQUEST);
  /* DMA0 TCD CH0_TCD0 initialization */
  EDMA_InstallTCD(DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL, (edma_tcd_t *)&DMA0_CH0_TCD0_CONFIG);
  /* DMA0 channel 0 peripheral request */
  EDMA_EnableChannelRequest(DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL);
}

/***********************************************************************************************************************
 * VREF0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'VREF0'
- type: 'vref_1'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'vref_1_2.4.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'VREF0'
- config_sets:
  - fsl_vref:
    - vref_config:
      - bufferMode: 'kVREF_ModeHighPowerBuffer'
      - enableLowPowerBuff: 'true'
      - enableInternalVoltageRegulator: 'true'
      - enableChopOscillator: 'true'
      - enableHCBandgap: 'true'
      - enableCurvatureCompensation: 'true'
      - initTrim: 'false'
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const vref_config_t VREF0_config = {
  .bufferMode = kVREF_ModeHighPowerBuffer,
  .enableLowPowerBuff = true,
  .enableInternalVoltageRegulator = true,
  .enableChopOscillator = true,
  .enableHCBandgap = true,
  .enableCurvatureCompensation = true
};

static void VREF0_init(void) {
  /* Power up analog module in SPC */
  SPC_EnableActiveModeAnalogModules(SPC0, kSPC_controlVref);
  /* VREF0 peripheral initialization */
  VREF_Init(VREF0_PERIPHERAL, &VREF0_config);
}

/***********************************************************************************************************************
 * ADC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC0'
- type: 'lpadc'
- mode: 'LPADC'
- custom_name_enabled: 'false'
- type_id: 'lpadc_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC0'
- config_sets:
  - fsl_lpadc:
    - lpadcConfig:
      - clockSource: 'AsynchronousFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - enableInDozeMode: 'false'
      - conversionAverageMode: 'kLPADC_ConversionAverage1'
      - offsetCalibration: 'no'
      - autoCalibrate: 'true'
      - enableAnalogPreliminary: 'true'
      - powerUpDelay: '0x80'
      - referenceVoltageSource: 'kLPADC_ReferenceVoltageAlt1'
      - powerLevelMode: 'kLPADC_PowerLevelAlt1'
      - triggerPriorityPolicy: 'kLPADC_ConvPreemptImmediatelyNotAutoResumed'
      - enableConvPause: 'false'
      - convPauseDelay: '0'
      - FIFO0Watermark: '0'
      - FIFO1Watermark: '0'
      - FIFO0WatermarkDMA: 'true'
      - FIFO1WatermarkDMA: 'false'
    - lpadcConvCommandConfig:
      - 0:
        - user_commandId: 'POT'
        - commandId: '1'
        - chainedNextCommandNumber: '2'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideA'
        - channelNumber: 'A.0'
        - enableChannelB_b: 'false'
        - channelBNumber: 'B.0'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount1'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK3'
        - hardwareCompareMode: 'kLPADC_HardwareCompareDisabled'
        - hardwareCompareValueHigh: '0'
        - hardwareCompareValueLow: '0'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionHigh'
        - enableWaitTrigger: 'false'
      - 1:
        - user_commandId: 'LIGHT'
        - commandId: '2'
        - chainedNextCommandNumber: '0'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideB'
        - channelNumber: 'B.0'
        - enableChannelB_b: 'false'
        - channelBNumber: 'B.0'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount1'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK3'
        - hardwareCompareMode: 'kLPADC_HardwareCompareDisabled'
        - hardwareCompareValueHigh: '0'
        - hardwareCompareValueLow: '0'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionHigh'
        - enableWaitTrigger: 'false'
    - lpadcConvTriggerConfig:
      - 0:
        - user_triggerId: ''
        - triggerId: '0'
        - targetCommandId: '1'
        - delayPower: '0'
        - priority: 'false'
        - channelAFIFOSelect: '0'
        - channelBFIFOSelect: '0'
        - enableHardwareTrigger: 'true'
    - IRQ_cfg:
      - interrupt_type: ''
      - enable_irq: 'false'
      - adc_interrupt:
        - IRQn: 'ADC0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'true'
        - priority: '3'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpadc_config_t ADC0_config = {
  .enableInDozeMode = false,
  .conversionAverageMode = kLPADC_ConversionAverage1,
  .enableAnalogPreliminary = true,
  .powerUpDelay = 0x80UL,
  .referenceVoltageSource = kLPADC_ReferenceVoltageAlt1,
  .powerLevelMode = kLPADC_PowerLevelAlt1,
  .triggerPriorityPolicy = kLPADC_ConvPreemptImmediatelyNotAutoResumed,
  .enableConvPause = false,
  .convPauseDelay = 0UL,
  .FIFO0Watermark = 0UL,
  .FIFO1Watermark = 0UL
};
lpadc_conv_command_config_t ADC0_commandsConfig[2] = {
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideA,
    .channelNumber = 0U,
    .channelBNumber = 0U,
    .chainedNextCommandNumber = 2,
    .enableChannelB = false,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount1,
    .sampleTimeMode = kLPADC_SampleTimeADCK3,
    .hardwareCompareMode = kLPADC_HardwareCompareDisabled,
    .hardwareCompareValueHigh = 0UL,
    .hardwareCompareValueLow = 0UL,
    .conversionResolutionMode = kLPADC_ConversionResolutionHigh,
    .enableWaitTrigger = false
  },
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideB,
    .channelNumber = 0U,
    .channelBNumber = 0U,
    .chainedNextCommandNumber = 0,
    .enableChannelB = false,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount1,
    .sampleTimeMode = kLPADC_SampleTimeADCK3,
    .hardwareCompareMode = kLPADC_HardwareCompareDisabled,
    .hardwareCompareValueHigh = 0UL,
    .hardwareCompareValueLow = 0UL,
    .conversionResolutionMode = kLPADC_ConversionResolutionHigh,
    .enableWaitTrigger = false
  }
};
lpadc_conv_trigger_config_t ADC0_triggersConfig[1] = {
  {
    .targetCommandId = 1,
    .delayPower = 0UL,
    .channelAFIFOSelect = 0,
    .channelBFIFOSelect = 0,
    .priority = 1,
    .enableHardwareTrigger = true
  }
};

static void ADC0_init(void) {
  /* Initialize LPADC converter */
  LPADC_Init(ADC0_PERIPHERAL, &ADC0_config);
  /* Perform auto calibration */
  LPADC_DoAutoCalibration(ADC0_PERIPHERAL);
  /* Enable DMA request on FIFO 0 watermark event */
  LPADC_EnableFIFO0WatermarkDMA(ADC0_PERIPHERAL, true);
  /* Configure conversion command 1. */
  LPADC_SetConvCommandConfig(ADC0_PERIPHERAL, ADC0_POT, &ADC0_commandsConfig[0]);
  /* Configure conversion command 2. */
  LPADC_SetConvCommandConfig(ADC0_PERIPHERAL, ADC0_LIGHT, &ADC0_commandsConfig[1]);
  /* Configure trigger 0. */
  LPADC_SetConvTriggerConfig(ADC0_PERIPHERAL, 0, &ADC0_triggersConfig[0]);
}

/***********************************************************************************************************************
 * CTIMER0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER0'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'false'
- type_id: 'ctimer_2.2.2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER0'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - timerPrescaler: '1 ms'
    - EnableTimerInInit: 'false'
    - matchChannels:
      - 0:
        - matchChannelPrefixId: 'Match_3'
        - matchChannel: 'kCTIMER_Match_3'
        - matchValueStr: '1 ms'
        - enableCounterReset: 'false'
        - enableCounterStop: 'false'
        - outControl: 'kCTIMER_Output_Toggle'
        - outPinInitValue: 'low'
        - enableInterrupt: 'false'
      - 1:
        - matchChannelPrefixId: 'Match_0'
        - matchChannel: 'kCTIMER_Match_0'
        - matchValueStr: '250 ms'
        - enableCounterReset: 'true'
        - enableCounterStop: 'false'
        - outControl: 'kCTIMER_Output_NoAction'
        - outPinInitValue: 'low'
        - enableInterrupt: 'true'
    - captureChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER0_IRQn'
        - enable_priority: 'true'
        - priority: '2'
      - callback: 'kCTIMER_SingleCallback'
      - singleCallback: 'ctimer0_callback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER0_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 47999
};
const ctimer_match_config_t CTIMER0_Match_3_config = {
  .matchValue = 0,
  .enableCounterReset = false,
  .enableCounterStop = false,
  .outControl = kCTIMER_Output_Toggle,
  .outPinInitState = false,
  .enableInterrupt = false
};
const ctimer_match_config_t CTIMER0_Match_0_config = {
  .matchValue = 249,
  .enableCounterReset = true,
  .enableCounterStop = false,
  .outControl = kCTIMER_Output_NoAction,
  .outPinInitState = false,
  .enableInterrupt = true
};
/* Single callback functions definition */
ctimer_callback_t CTIMER0_callback[] = {ctimer0_callback};

static void CTIMER0_init(void) {
  /* CTIMER0 peripheral initialization */
  CTIMER_Init(CTIMER0_PERIPHERAL, &CTIMER0_config);
  /* Interrupt vector CTIMER0_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(CTIMER0_TIMER_IRQN, CTIMER0_TIMER_IRQ_PRIORITY);
  /* Match channel 3 of CTIMER0 peripheral initialization */
  CTIMER_SetupMatch(CTIMER0_PERIPHERAL, CTIMER0_MATCH_3_CHANNEL, &CTIMER0_Match_3_config);
  /* Match channel 0 of CTIMER0 peripheral initialization */
  CTIMER_SetupMatch(CTIMER0_PERIPHERAL, CTIMER0_MATCH_0_CHANNEL, &CTIMER0_Match_0_config);
  CTIMER_RegisterCallBack(CTIMER0_PERIPHERAL, CTIMER0_callback, kCTIMER_SingleCallback);
}

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
    - interrupts:
      - 0:
        - channelId: 'int_0'
        - interrupt_t:
          - IRQn: 'EDMA_0_CH1_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'true'
          - priority: '2'
          - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * GPIO2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO2'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_2.7.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO2'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'GPIO20_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '2'
      - enable_custom_name: 'false'
    - enable_irq_1: 'false'
    - gpio_interrupt_1:
      - IRQn: 'GPIO01_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '1'
      - enable_custom_name: 'false'
    - enable_irq_EFT: 'false'
    - port_interrupt_EFT:
      - IRQn: 'noInt'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '2'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO2_init(void) {
  /* Make sure, the clock gate for port 2 is enabled (e. g. in pin_mux.c) */
  /* Interrupt vector GPIO20_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(GPIO2_INT_0_IRQN, GPIO2_INT_0_IRQ_PRIORITY);
  /* Enable interrupt GPIO2_INT_0_IRQN request in the NVIC */
  EnableIRQ(GPIO2_INT_0_IRQN);
}

/***********************************************************************************************************************
 * GPIO1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO1'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_2.7.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO1'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'GPIO10_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '2'
      - enable_custom_name: 'false'
    - enable_irq_1: 'false'
    - gpio_interrupt_1:
      - IRQn: 'GPIO01_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '1'
      - enable_custom_name: 'false'
    - enable_irq_EFT: 'false'
    - port_interrupt_EFT:
      - IRQn: 'noInt'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '2'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO1_init(void) {
  /* Make sure, the clock gate for port 1 is enabled (e. g. in pin_mux.c) */
  /* Interrupt vector GPIO10_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(GPIO1_INT_0_IRQN, GPIO1_INT_0_IRQ_PRIORITY);
  /* Enable interrupt GPIO1_INT_0_IRQN request in the NVIC */
  EnableIRQ(GPIO1_INT_0_IRQN);
}

/***********************************************************************************************************************
 * GPIO4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO4'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_2.7.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO4'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'GPIO40_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '2'
      - enable_custom_name: 'false'
    - enable_irq_1: 'false'
    - gpio_interrupt_1:
      - IRQn: 'GPIO01_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '1'
      - enable_custom_name: 'false'
    - enable_irq_EFT: 'false'
    - port_interrupt_EFT:
      - IRQn: 'noInt'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '2'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO4_init(void) {
  /* Make sure, the clock gate for port 4 is enabled (e. g. in pin_mux.c) */
  /* Interrupt vector GPIO40_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(GPIO4_INT_0_IRQN, GPIO4_INT_0_IRQ_PRIORITY);
  /* Enable interrupt GPIO4_INT_0_IRQN request in the NVIC */
  EnableIRQ(GPIO4_INT_0_IRQN);
}

/***********************************************************************************************************************
 * LP_FLEXCOMM2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LP_FLEXCOMM2'
- type: 'lpflexcomm_lpi2c'
- mode: 'edma_transfer'
- custom_name_enabled: 'false'
- type_id: 'lpflexcomm_lpi2c_2.1.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LP_FLEXCOMM2'
- config_sets:
  - transferEDMACfg:
    - master_transfer:
      - handle: 'default'
      - init_callback: 'true'
      - callback:
        - name: 'lpi2c_master_callback'
        - userData: ''
      - init_transfer: 'false'
      - transfer:
        - flagsSet: ''
        - slaveAddress: '0'
        - direction: 'kLPI2C_Write'
        - subaddress: '0'
        - subaddressSize: '1'
        - data: 'custom:buffer'
        - data_size_i: '1024'
    - channel_rx_init: 'true'
    - channel_rx:
      - uid: '1774181647316'
      - eDMAn: '2'
      - eDMA_source: 'kDma0RequestMuxLpFlexcomm2Rx'
      - init_channel_priority: 'false'
      - edma_channel_Preemption:
        - enableChannelPreemption: 'false'
        - enablePreemptAbility: 'false'
        - channelPriority: '0'
      - masterIdReplicationEnable: 'noInit'
      - securityLevel: 'noInit'
      - protectionLevel: 'noInit'
      - enable_custom_name: 'false'
    - channel_tx_init: 'true'
    - channel_tx:
      - uid: '1774181647323'
      - eDMAn: '1'
      - eDMA_source: 'kDma0RequestMuxLpFlexcomm2Tx'
      - init_channel_priority: 'false'
      - edma_channel_Preemption:
        - enableChannelPreemption: 'false'
        - enablePreemptAbility: 'false'
        - channelPriority: '0'
      - masterIdReplicationEnable: 'noInit'
      - securityLevel: 'noInit'
      - protectionLevel: 'noInit'
      - enable_custom_name: 'false'
  - generalCfg:
    - lpi2c_mode: 'master'
    - clock_configuration:
      - clockSource: 'LPFLEXCOMMFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - master_config:
      - enableMaster: 'true'
      - enableDoze: 'true'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '100000'
      - realBaudRateCount: []
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t LP_FLEXCOMM2_masterConfig = {
  .enableMaster = true,
  .enableDoze = true,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 100000UL,
  .busIdleTimeout_ns = 0UL,
  .pinLowTimeout_ns = 0UL,
  .sdaGlitchFilterWidth_ns = 0U,
  .sclGlitchFilterWidth_ns = 0U,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};
edma_handle_t LP_FLEXCOMM2_RX_Handle;
edma_handle_t LP_FLEXCOMM2_TX_Handle;
lpi2c_master_edma_handle_t LP_FLEXCOMM2_master_handle;

static void LP_FLEXCOMM2_init(void) {
  /* LP_FLEXCOMM2 LPI2C leader initialization */
  LPI2C_MasterInit(LP_FLEXCOMM2_PERIPHERAL, &LP_FLEXCOMM2_masterConfig, LP_FLEXCOMM2_CLOCK_SOURCE);
  /* Set the kDma0RequestMuxLpFlexcomm2Rx request */
  EDMA_SetChannelMux(LP_FLEXCOMM2_RX_DMA_BASEADDR, LP_FLEXCOMM2_RX_DMA_CHANNEL, LP_FLEXCOMM2_RX_DMA_REQUEST);
  /* Set the kDma0RequestMuxLpFlexcomm2Tx request */
  EDMA_SetChannelMux(LP_FLEXCOMM2_TX_DMA_BASEADDR, LP_FLEXCOMM2_TX_DMA_CHANNEL, LP_FLEXCOMM2_TX_DMA_REQUEST);
  /* Create the eDMA LP_FLEXCOMM2_RX_Handle handle */
  EDMA_CreateHandle(&LP_FLEXCOMM2_RX_Handle, LP_FLEXCOMM2_RX_DMA_BASEADDR, LP_FLEXCOMM2_RX_DMA_CHANNEL);
  /* Create the eDMA LP_FLEXCOMM2_TX_Handle handle */
  EDMA_CreateHandle(&LP_FLEXCOMM2_TX_Handle, LP_FLEXCOMM2_TX_DMA_BASEADDR, LP_FLEXCOMM2_TX_DMA_CHANNEL);
  /* Create eDMA leader transfer handle */
  LPI2C_MasterCreateEDMAHandle(LP_FLEXCOMM2_PERIPHERAL, &LP_FLEXCOMM2_master_handle, &LP_FLEXCOMM2_RX_Handle, &LP_FLEXCOMM2_TX_Handle, lpi2c_master_callback, NULL);

}

/***********************************************************************************************************************
 * GPIO3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO3'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_2.7.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO3'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'GPIO30_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '2'
      - enable_custom_name: 'false'
    - enable_irq_1: 'false'
    - gpio_interrupt_1:
      - IRQn: 'GPIO01_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '1'
      - enable_custom_name: 'false'
    - enable_irq_EFT: 'false'
    - port_interrupt_EFT:
      - IRQn: 'noInt'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '2'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO3_init(void) {
  /* Make sure, the clock gate for port 3 is enabled (e. g. in pin_mux.c) */
  /* Interrupt vector GPIO30_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(GPIO3_INT_0_IRQN, GPIO3_INT_0_IRQ_PRIORITY);
  /* Enable interrupt GPIO3_INT_0_IRQN request in the NVIC */
  EnableIRQ(GPIO3_INT_0_IRQN);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
static void BOARD_InitPeripherals_CommonPostInit(void)
{
  /* Interrupt vector EDMA_0_CH1_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(INT_0_IRQN, INT_0_IRQ_PRIORITY);
  /* Enable interrupt INT_0_IRQN request in the NVIC */
  EnableIRQ(INT_0_IRQN);
}

void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  (void)memset(DMA0_config.channelConfig, 0, FSL_FEATURE_EDMA_INSTANCE_CHANNELn(DMA0_DMA_BASEADDR) * sizeof(edma_channel_config_t *));
  EDMA_Init(DMA0_DMA_BASEADDR, &DMA0_config);

  /* Initialize components */
  DMA0_init();
  VREF0_init();
  ADC0_init();
  CTIMER0_init();
  GPIO2_init();
  GPIO1_init();
  GPIO4_init();
  LP_FLEXCOMM2_init();
  GPIO3_init();
  /* Common post-initialization */
  BOARD_InitPeripherals_CommonPostInit();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
